name: Remote shell
on: [workflow_dispatch]
jobs:
  run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup upterm session
        uses: owenthereal/action-upterm@v1
        with:
          limit-access-to-users: emassey0135
